logo: "https://raw.githubusercontent.com/nuuday/source-code-consolidation/master/docs/assets/nuuday.png?token=AO5EFQYXVUK6PD2JPIBVXCS6RXINM"
remote_theme: pmarsceill/just-the-docs
title: "Engineering Ways of Working"
search_enabled: true
heading_anchors: true
